name: mdsine2
channels:
  - etetoolkit
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.7
  - ete3=3.1.2
  - pip
  - pip:
    - PySide2==5.15.2
    - git+git://github.com/gerberlab/MDSINE2@master
